<?php
/** @var $block \Magento\Framework\View\Element\Template **/
?>
<?php
    $_themeHelper = $this->helper('\Unet\SocialShare\Helper\Data');
    $baseUrl = $_themeHelper->getBaseUrl();
    $site = $_themeHelper->getStoreName();

    $type= $block->getPageType();
    $title = $block->getPageTitle();
    $description = $block->getPageDescription();
    $image = $block->getPageImage();
    $url = $block->getPageUrl();
    $canonicalUrl = $block->getCanonicalUrl();

    $language = $_themeHelper->getLanguage();
    $facebookAppId = $_themeHelper->getStoreConfig('social_share/facebook/facebook_app_id');
    $twitterSite = $_themeHelper->getStoreConfig('social_share/twitter/twitter_site_name');
?>

<?php if ($language == \Unet\SocialShare\Helper\Data::MAIN_LANGUAGE): ?>
    <link rel="alternate" href="<?php /* @escapeNotVerified */ echo $block->escapeHtml($baseUrl); ?>" hreflang="x-default" />
<?php else: ?>
    <link rel="alternate" href="<?php /* @escapeNotVerified */ echo $block->escapeHtml($baseUrl); ?>" hreflang="<?php /* @escapeNotVerified */ echo $language; ?>" />
<?php endif; ?>
<link rel="canonical" href="<?php /* @escapeNotVerified */ echo $block->escapeHtml($canonicalUrl); ?>" />

<!-- Open Graph data -->
<meta property="og:type" content="<?php /* @escapeNotVerified */ echo $type; ?>" />
<meta property="og:title" content="<?php /* @escapeNotVerified */ echo $block->escapeHtml($title); ?>" />
<meta property="og:image" content="<?php /* @escapeNotVerified */ echo $block->escapeHtml($image); ?>" />
<meta property="og:image:secure_url" content="<?php /* @escapeNotVerified */ echo $block->escapeHtml($image); ?>" />
<meta property="og:image:width" content="<?php /* @escapeNotVerified */ echo \Unet\SocialShare\Adapter\SocialAdapter::IMAGE_WIDTH; ?>" />
<meta property="og:image:height" content="<?php /* @escapeNotVerified */ echo \Unet\SocialShare\Adapter\SocialAdapter::IMAGE_HEIGHT; ?>" />
<meta property="og:description" content="<?php /* @escapeNotVerified */ echo $block->escapeHtml($description); ?>" />
<meta property="og:url" content="<?php /* @escapeNotVerified */ echo $block->escapeHtml($url); ?>" />

<?php if (!empty($facebookAppId)): ?>
    <meta property="fb:app_id" content="<?php /* @escapeNotVerified */ echo $block->escapeHtml($facebookAppId); ?>" />
<?php endif;?>

<!-- Twitter Card data -->
<meta name="twitter:card" content="<?php /* @escapeNotVerified */ echo 'summary'; ?>" />

<?php if (!empty($twitterSite)): ?>
    <meta name="twitter:site" content="<?php /* @escapeNotVerified */ echo '@'.$block->escapeHtml($twitterSite); ?>" />
<?php endif; ?>

<meta name="twitter:title" content="<?php /* @escapeNotVerified */ echo $block->escapeHtml($title); ?>" />
<meta name="twitter:description" content="<?php /* @escapeNotVerified */ echo $block->escapeHtml($description); ?>" />
<meta name="twitter:image" content="<?php /* @escapeNotVerified */ echo $block->escapeHtml($image); ?>" />
